spring.application.name=Prep_tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:prep_db}?options=-c%20TimeZone=UTC
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver